mass_api:
    resource: "@MassAPIBundle/Resources/config/routing.yml"
    prefix:   /

api:
    resource: "."
    type:     "api"

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   "/doc"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
