admin_dashboard:
    path: /
    defaults:
        _controller: vf.controller.location:indexAction
        _sylius:
            template: 'FrontBundle:Admin:dashboard.html.twig'
            paginate: false

admin_country:
    resource: "@MassAPIBundle/Resources/config/routing/admin/country.yml"
    prefix: /country

admin_event:
    resource: "@MassAPIBundle/Resources/config/routing/admin/event.yml"
    prefix: /event

admin_place:
    resource: "@MassAPIBundle/Resources/config/routing/admin/place.yml"
    prefix: /place
