services:
    mass_api.form.place:
        class: MassAPIBundle\Form\Type\PlaceType
        tags:
            - { name: form.type, alias: mass_api_place }

    mass_api.form.event:
        class: MassAPIBundle\Form\Type\EventType
        tags:
            - { name: form.type, alias: mass_api_event }

    mass_api.form.postal_address:
        class: MassAPIBundle\Form\Type\PostalAddressType
        tags:
            - { name: form.type, alias: mass_api_postal_address }
