home:
    path: /
    defaults:
        _controller: MassAPIBundle:Home:index

result:
    path: /result/{postalCode}
    defaults:
        _controller: MassAPIBundle:Home:result

map:
    path: /map/{postalCode}
    defaults:
        _controller: MassAPIBundle:Home:map

place:
    path: /places
    defaults:
        _controller: MassAPIBundle:Home:nearPlace
    options:
        expose: true

admin:
    resource: "@MassAPIBundle/Resources/config/routing/admin.yml"
    prefix: /admin
